// This file is generated by Slice Machine. Update with care!

import Slug from './Slug';
import TextBlock from './TextBlock';

export {
	Slug,
	TextBlock,
};

export const components = {
	slug: Slug,
	text_block: TextBlock,
};
